services:
  web:
    build:
      context: ./php
      args:
        DEV_MODE: ${DEV_MODE:-false}
    ports:
      - "8080:80"
    volumes:
      - ./php/app:/var/www/html
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=testdb
      - MONGO_URI=mongodb://mongo:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
      - mongo

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d